-- ============================================================================
-- 0006_files_share_title.sql — 分享标题（files.share_title）
-- ============================================================================
--
-- ⚠️ 本文件由 scripts/gen-migrations.py 从 functions/utils/schema.js
--    **自动生成**，请勿手工编辑（改动会被覆盖）。
--
--    运行时并不需要本文件 —— Cloudflare Pages Functions 没有文件系统，
--    读不到 .sql；实际建表由 schema.js 的 ensureSchema() 在首次访问 D1 时
--    自动完成（懒迁移）。本文件仅用于人工排查与本地兜底。
--
--    唯一来源：functions/utils/schema.js
--    重新生成：python3 scripts/gen-migrations.py
--
-- 背景：分享此前只有"系统给的名字"——单文件分享显示真实文件名，既不能
--       给访客一个更好懂的标题，也无处附一句说明。
--
-- 本列是单文件分享的**展示标题**（KV metadata 里的 shareTitle）。
-- 允许为 NULL：NULL 表示"回退到真实文件名"，存量数据因此零改动即可工作。
--
-- 为什么允许为空而不回填：分享标题是**可选增强**。强制必填会让每次创建
--       分享都要先想个名字；把回退逻辑放在读取侧（接口与页面各一处）
--       比在写入侧给历史数据造标题便宜得多。
--
-- ⚠️ ALTER TABLE ADD COLUMN 不幂等，靠 schema.js 的 guard 保护。
--    刻意**每条列一个迁移**：若四条 ALTER 挤在同一条迁移里，一旦出现
--    "files 已加列、bundles 未加列"的半应用状态，重跑时第一条 ALTER 就会
--    抛 duplicate column name，整段迁移失败且版本不被标记 —— 迁移将卡死。
-- ============================================================================

ALTER TABLE files ADD COLUMN share_title TEXT;
